USE HR_Applications;

SELECT * FROM Sales_ecommerce;


-- What are the total gross sales, total discounts, net sales, and total profit generated by the business?

SELECT
	ROUND(SUM(gross_sales), 2) AS total_gross_sales,
	ROUND(SUM(discount_amount), 2) AS total_discounts,
	ROUND(SUM(net_sales), 2) AS total_net_sales,
	ROUND(SUM(profit), 2) AS total_profit
FROM Sales_ecommerce;


-- Which 10 countries generate the highest net sales?

CREATE View Top_10_Countries_by_net_sales AS
SELECT 
	TOP 10 customer_country,
	ROUND(SUM(net_sales), 2) AS total_net_sales
FROM Sales_ecommerce
GROUP BY customer_country
ORDER BY total_net_sales DESC;


-- Which customer segments generate the highest total profit and profit margin?

CREATE View Best_Customer_Segments_Profit AS
SELECT 
	customer_segment,
	ROUND(SUM(profit), 2) AS total_profit,
	ROUND(AVG(profit_margin_percentage), 2) AS avg_profit_margin
FROM Sales_ecommerce
GROUP BY customer_segment;


-- Which marketing channels generate the highest net sales and profit?

CREATE View Best_Marketing_Channels_Profit AS
SELECT 
	marketing_channel,
	ROUND(SUM(profit), 2) AS total_profit,
	ROUND(SUM(net_sales), 2) AS total_net_sales
FROM Sales_ecommerce
GROUP BY marketing_channel;


-- What percentage of orders are repeat-customer orders, and how does their average order value compare with new customers?

SELECT
    CASE WHEN is_repeat_customer = 'True' THEN 'Repeat' ELSE 'New' END AS customer_group,
    COUNT(*)                                                   AS orders,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 2)         AS pct_of_orders,
    ROUND(AVG(net_sales), 2)                                   AS avg_order_value
FROM Sales_ecommerce
GROUP BY is_repeat_customer
ORDER BY is_repeat_customer DESC;


-- Which 10 customers have the highest customer lifetime value, and how many orders has each customer made?

CREATE VIEW top_10_customer_lifetimevalue_and_orders AS
SELECT
	TOP 10 customer_name,
	ROUND(AVG(customer_lifetime_value), 2) AS avg_lifetime_value,
	SUM(customer_order_count) AS total_orders_made
FROM Sales_ecommerce
GROUP BY customer_name
ORDER BY avg_lifetime_value DESC;


-- Which shipping methods have the highest average delivery delay, and how does their customer rating compare?

SELECT 
	shipping_method,
	ROUND(AVG(CAST(delivery_days - estimated_delivery_days AS FLOAT)), 2) AS avg_delivery_delay,
	ROUND(AVG(CAST(customer_rating AS FLOAT)), 2)                         AS avg_customer_rating
FROM dbo.Sales_ecommerce
WHERE order_status = 'Completed'
GROUP BY shipping_method
ORDER BY avg_delivery_delay DESC;


-- Which campaigns generate the highest profit after accounting for discounts?

CREATE View best_campaigns_profit AS
SELECT
	TOP 18 COALESCE(campaign_name, 'No campaign') AS campaign,
	COUNT(*) AS orders,
	ROUND(SUM(gross_sales - discount_amount - product_cost), 0) AS profit_after_discount
FROM Sales_ecommerce
WHERE order_status = 'Completed'
GROUP BY COALESCE(campaign_name, 'No campaign')
ORDER BY profit_after_discount DESC;


-- which month generated the highest profit?

CREATE View best_months_performance AS
SELECT
	TOP 12 DATENAME(MONTH, order_date) AS order_month,
	ROUND(SUM(gross_sales - discount_amount), 0) AS net_sales,
	ROUND(SUM(gross_sales - discount_amount - product_cost), 0) AS profit
FROM Sales_ecommerce
WHERE order_status = 'Completed'
GROUP BY DATENAME(MONTH, order_date), MONTH(order_date)
ORDER BY MONTH(order_date);